version: '3.4'

services:
  mtrabbitmq:
    image: masstransit/rabbitmq

  redis-cache:
    image: redis:latest

  mtsample.webapi:
    image: ${DOCKER_REGISTRY-}mtsamplewebapi
    build:
      context: .
      dockerfile: MTSample.WebApi/Dockerfile
    depends_on:
    - mtsample.backgroundworker-1
    - mtsample.backgroundworker-2
    - mtsample.backgroundworker-3
    - mtrabbitmq

  mtsample.backgroundworker-1:
    image: ${DOCKER_REGISTRY-}mtsamplebackgroundworker
    build:
      context: .
      dockerfile: MTSample.BackgroundWorker/Dockerfile
    depends_on:
      - mtrabbitmq
      
  mtsample.backgroundworker-2:
    image: ${DOCKER_REGISTRY-}mtsamplebackgroundworker
    build:
      context: .
      dockerfile: MTSample.BackgroundWorker/Dockerfile
    depends_on:
      - mtrabbitmq

  mtsample.backgroundworker-3:
    image: ${DOCKER_REGISTRY-}mtsamplebackgroundworker
    build:
      context: .
      dockerfile: MTSample.BackgroundWorker/Dockerfile
    depends_on:
      - mtrabbitmq