version: '3.4'

services:
  masstransit.rabbitmq:
    image: masstransit/rabbitmq
    ports:
      - "15672"

  redis-cache:
    image: redis:latest

  mtsample.webapi:
    image: ghcr.io/espiya/mtsample.webapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"
    depends_on:
    - redis-cache
    - masstransit.rabbitmq
    - mtsample.backgroundworker

  mtsample.backgroundworker:
    image: ghcr.io/espiya/mtsample.backgroundworker:latest
    environment:
      - DOTNET_ENVIRONMENT=Development
    deploy:
      replicas: 5
    depends_on:
    - redis-cache
    - masstransit.rabbitmq