apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtsample-backgroundworker
spec:
  selector:
    matchLabels:
      app: mtsample-backgroundworker
  replicas: 3
  template:
    metadata:
      labels:
        app: mtsample-backgroundworker
    spec:
      containers:
      - name: mtsample-backgroundworker
        image: ghcr.io/espiya/mtsample.backgroundworker:latest
        envFrom:
        - configMapRef:
            name: mtsample-configmap