apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtrabbitmq
spec:
  selector:
    matchLabels:
      app: mtrabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: mtrabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: masstransit/rabbitmq
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
      volumes:
      - name: rabbitmq-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mtrabbitmq
spec:
  selector:
    app: mtrabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
