apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtsample-webapi
spec:
  selector:
    matchLabels:
      app: mtsample-webapi
  replicas: 1
  template:
    metadata:
      labels:
        app: mtsample-webapi
    spec:
      containers:
      - name: mtsample-webapi
        image: ghcr.io/espiya/mtsample.webapi:latest
        env:
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: mtsample-webapi
spec:
  selector:
    app: mtsample-webapi
  ports:
  - name: http
    port: 8080
    targetPort: 8080