name: Build and Push Docker Image - MTSample.WebApi

on:
  push:
    branches: [ "master" ]
    paths:
      - 'MTSample.WebApi/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64
        builder: ${{ steps.buildx.outputs.name }}
        tags: ghcr.io/espiya/mtsample.webapi:latest
        file: MTSample.WebApi/Dockerfile
